from typing import Protocol, List, Dict, Any

class InterfacePago(Protocol):
    def procesar_pago(self, id_vehiculo: int, pago: float) -> Dict[str, Any]:...
    '''
    def obtener_pagos(self) -> List[Dict[str, Any]]: ...
    def obtener_pago_por_id(self, id_pago: int) -> Dict[str, Any]:...
    def cancelar_pago(self, id_pago: int) -> bool:...
    '''