from typing import Protocol, List, Dict, Any

class InterfaceTipoVehiculo(Protocol):
    def listarTodos(self) -> List[Dict[str, Any]]: ...
    def listarActivos(self) -> List[Dict[str, Any]]: ...
    def obtenerPorId(self, id_tipovehiculo: int) -> Dict[str, Any]: ...
    def crear(self, nombre: str, tarifa: float, limite: int) -> int: ...
    def actualizar(self, id_tipovehiculo: int, nombre: str, tarifa:float, limite: int, estado: bool) -> Dict[str, Any]: ...
    def cambiarEstado(self, tipo_vehiculo_id: int) -> Dict[str, Any]: ...