from typing import Protocol, List, Dict, Any

class InterfaceVehiculo(Protocol):
    def listar(self) -> List[Dict[str, Any]]: ...
    def crear(self, tipoVehiculo:int,placa:str,documento:str,nombre:str) -> int: ...
    def cambiar_estado(self,vehiculo_id: str) -> Dict[str, Any]: ...
    def actualizar(self, id_vehiculo: int, id_tipovehiculo: int, placa: str, documento: str, nombre: str, estado: bool) -> Dict[str, Any]: ...
    def eliminar(self, vehiculo_id: int) -> Dict[str, Any]: ... 