from typing import Protocol, List, Dict, Any

class InterfaceVehiculo(Protocol):
    def listar(self) -> List[Dict[str, Any]]: ...
    def crear(self, tipoVehiculo:int,placa:str,documento:str,nombre:str) -> int: ...